image: ubuntu:bionic

variables:
  DOCS_PATH: "/mnt/docs"
  CC: "clang"
  CXX: "clang++"
  DEBIAN_FRONTEND: "noninteractive"
  DEBCONF_NONINTERACTIVE_SEEN: "true"
  LANG: "C"
  npm_config_cache: ".npm"

stages:
  - build
  - test
  - deploy

run_make:
  stage: build
  before_script:
    - apt-get update
    - apt-get -y -q install --no-install-recommends build-essential
  script:
    - make bootstrap
    - mkdir -p build
    - cd build && cmake .. -DBUILD_LIBUSB=ON -DBUILD_DOC=ON
    - make
  artifacts:
    name: $CI_COMMIT_REF_NAME
    paths:
      - build/
    
run_tests:
  stage: test
  before_script:
  - apt-get update
  - apt-get -y -q install --no-install-recommends build-essential
  script:
    - make bootstrap
    - make test
  dependencies:
    - run_make

deploy_docs:
  stage: deploy
  script:
    - mkdir -p "$DOCS_PATH/librpc"
    - rm -rf "$DOCS_PATH/librpc/*"
    - cp -R build/docs/* "$DOCS_PATH/librpc/"
  dependencies:
    - run_make



