# This will run on Travis' 'new' container-based infrastructure
sudo: required
language: c++
services:
  - docker

# Whitelist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - DOXYFILE_IN: $TRAVIS_BUILD_DIR/Doxyfile.in
    - DOCKER_IMAGE: ubuntu:16.04
    - PACKAGES: doxygen doxygen-doc doxygen-latex doxygen-gui graphviz cmake clang libglib2.0-dev libsoup2.4-dev libyajl-dev libyaml-dev libyaml-dev libusb-1.0-0-dev

before_install:
  - docker pull ${DOCKER_IMAGE}
  - docker create --name builder -v $(pwd):/code ${DOCKER_IMAGE}

# Install dependencies
before_script:
  - docker exec builder /bin/bash -c "DEBIAN_FRONTEND=noninteractive apt-get -yq update"
  - docker exec builder /bin/bash -c "DEBIAN_FRONTEND=noninteractive apt-get -yq --no-install-recommends --no-install-suggests --force-yes install ${PACKAGES}"

# Build your code e.g. by calling make
script:
  - docker exec builder /bin/bash -c 'cd /code && mkdir build'
  - docker exec builder /bin/bash -c 'cd /code/build && cmake .. -DBUILD_BUS=OFF -DBUILD_LIBUSB=ON -DPYTHON_VERSION=2'
  - docker exec builder /bin/bash -c 'cd /code/build && make'
  - docker exec builder /bin/bash -c 'cd /code && sh tools/deploy-docs.sh'

