# This will run on Travis' 'new' container-based infrastructure
sudo: false
dist: trusty

# Whitelist
branches:
  only:
    - master

# Environment variables
env:
  global:
    - DOXYFILE_IN: $TRAVIS_BUILD_DIR/Doxyfile.in

# Install dependencies
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - cmake
      - clang
      - libglib2.0-dev
      - libsoup-gnome2.4-dev
      - libyajl-dev
      - libblocksruntime-dev

# Build your code e.g. by calling make
script:
  - cd $TRAVIS_BUILD_DIR
  - sh tools/deploy-docs.sh
